// Sprint 6 bit-width optimization variant of tb_accelerator.sv: the SAME
// rtl/accelerator_top.sv, controller.sv, processing_element.sv,
// requantize.sv -- no new/forked RTL -- instantiated with DATA_WIDTH=4
// instead of 8 (see docs/optimization_plan.md). NUM_INPUTS, NUM_NEURONS,
// ACC_WIDTH, and SHIFT_WIDTH are all unchanged from the INT8 baseline:
// this testbench isolates precision as the only variable, per
// docs/research_methodology.md's "change one architectural variable at
// a time".
//
// Loads all 5 rows of verification/reference/vectors_int4.csv (real
// output of algorithm/generate_vectors.py's INT4 path, seed=1234,
// shift=4) and checks the accelerator's four INT4 outputs, packed into
// signed 4-bit lanes of y_out, against what Python actually computed --
// both the pre-ReLU/pre-requantize INT32 accumulator and the final
// requantized output, exactly like tb_accelerator.sv does for INT8.
`ifndef DUMPFILE
`define DUMPFILE "tb_accelerator_int4.vcd"
`endif

module tb_accelerator_int4;

    localparam int DATA_WIDTH  = 4;   // the one parameter this variant changes
    localparam int NUM_INPUTS  = 8;
    localparam int NUM_NEURONS = 4;
    localparam int ACC_WIDTH   = 32;
    localparam int SHIFT_WIDTH = 5;

    logic clk, rst_n, start;
    logic weight_wr_en;
    logic [$clog2(NUM_NEURONS)-1:0] weight_wr_pe;
    logic [$clog2(NUM_INPUTS)-1:0]  weight_wr_idx;
    logic signed [DATA_WIDTH-1:0]   weight_wr_data;
    logic act_wr_en;
    logic [$clog2(NUM_INPUTS)-1:0]  act_wr_idx;
    logic signed [DATA_WIDTH-1:0]   act_wr_data;
    logic bias_wr_en;
    logic [$clog2(NUM_NEURONS)-1:0] bias_wr_pe;
    logic signed [ACC_WIDTH-1:0]    bias_wr_data;
    logic [SHIFT_WIDTH-1:0]         shift_in;
    logic busy, done;
    logic [NUM_NEURONS*DATA_WIDTH-1:0] y_out;

    accelerator_top #(
        .DATA_WIDTH (DATA_WIDTH),
        .NUM_INPUTS (NUM_INPUTS),
        .NUM_NEURONS(NUM_NEURONS),
        .ACC_WIDTH  (ACC_WIDTH),
        .SHIFT_WIDTH(SHIFT_WIDTH)
    ) dut (
        .clk           (clk),
        .rst_n         (rst_n),
        .start         (start),
        .weight_wr_en  (weight_wr_en),
        .weight_wr_pe  (weight_wr_pe),
        .weight_wr_idx (weight_wr_idx),
        .weight_wr_data(weight_wr_data),
        .act_wr_en     (act_wr_en),
        .act_wr_idx    (act_wr_idx),
        .act_wr_data   (act_wr_data),
        .bias_wr_en    (bias_wr_en),
        .bias_wr_pe    (bias_wr_pe),
        .bias_wr_data  (bias_wr_data),
        .shift_in      (shift_in),
        .busy          (busy),
        .done          (done),
        .y_out         (y_out)
    );

    always #5 clk = ~clk;

    int pass_count = 0;
    int fail_count = 0;

    // ---- Golden vectors: verification/reference/vectors_int4.csv rows 1-5 --
    // (generated by algorithm/generate_vectors.py's INT4 path, seed=1234,
    // shift=4; transcribed here by a one-off script reading the CSV
    // directly, not retyped by hand, to avoid a transcription mismatch)
    localparam int NUM_VECTORS = 5;
    int x [0:NUM_VECTORS-1][0:7];
    int w [0:NUM_VECTORS-1][0:7][0:3];   // w[vec][i][j]
    int b [0:NUM_VECTORS-1][0:3];
    int exp_acc [0:NUM_VECTORS-1][0:3];
    int exp_y   [0:NUM_VECTORS-1][0:3];

    int vec;   // currently loaded vector index, used by write_*/check_neuron

    task automatic load_all_vectors;
        // vector 0
        x[0][0]=7; x[0][1]=7; x[0][2]=7; x[0][3]=-2;
        x[0][4]=-6; x[0][5]=6; x[0][6]=-7; x[0][7]=-4;
        w[0][0][0]=-6; w[0][0][1]=-3; w[0][0][2]=0; w[0][0][3]=-7;
        w[0][1][0]=4; w[0][1][1]=-5; w[0][1][2]=4; w[0][1][3]=-3;
        w[0][2][0]=4; w[0][2][1]=7; w[0][2][2]=7; w[0][2][3]=-4;
        w[0][3][0]=0; w[0][3][1]=-1; w[0][3][2]=-4; w[0][3][3]=1;
        w[0][4][0]=6; w[0][4][1]=5; w[0][4][2]=2; w[0][4][3]=5;
        w[0][5][0]=0; w[0][5][1]=2; w[0][5][2]=7; w[0][5][3]=2;
        w[0][6][0]=-8; w[0][6][1]=3; w[0][6][2]=3; w[0][6][3]=-5;
        w[0][7][0]=5; w[0][7][1]=-6; w[0][7][2]=4; w[0][7][3]=5;
        b[0][0]=-1; b[0][1]=-4; b[0][2]=-3; b[0][3]=1;
        exp_acc[0][0]=13; exp_acc[0][1]=-24; exp_acc[0][2]=75; exp_acc[0][3]=-102;
        exp_y[0][0]=1;   exp_y[0][1]=0;   exp_y[0][2]=5;   exp_y[0][3]=0;

        // vector 1 -- exercises the INT4_MIN weight/activation boundary (-8)
        x[1][0]=-8; x[1][1]=2; x[1][2]=-6; x[1][3]=1;
        x[1][4]=0; x[1][5]=-8; x[1][6]=-6; x[1][7]=7;
        w[1][0][0]=-2; w[1][0][1]=-1; w[1][0][2]=-1; w[1][0][3]=0;
        w[1][1][0]=-5; w[1][1][1]=-8; w[1][1][2]=2; w[1][1][3]=-4;
        w[1][2][0]=2; w[1][2][1]=5; w[1][2][2]=-2; w[1][2][3]=-2;
        w[1][3][0]=-6; w[1][3][1]=3; w[1][3][2]=3; w[1][3][3]=6;
        w[1][4][0]=4; w[1][4][1]=-6; w[1][4][2]=4; w[1][4][3]=7;
        w[1][5][0]=-3; w[1][5][1]=-6; w[1][5][2]=5; w[1][5][3]=7;
        w[1][6][0]=7; w[1][6][1]=-7; w[1][6][2]=6; w[1][6][3]=-1;
        w[1][7][0]=-2; w[1][7][1]=5; w[1][7][2]=6; w[1][7][3]=-4;
        b[1][0]=2; b[1][1]=2; b[1][2]=2; b[1][3]=3;
        exp_acc[1][0]=-42; exp_acc[1][1]=92; exp_acc[1][2]=-5; exp_acc[1][3]=-65;
        exp_y[1][0]=0;   exp_y[1][1]=6;   exp_y[1][2]=0;   exp_y[1][3]=0;

        // vector 2
        x[2][0]=-3; x[2][1]=5; x[2][2]=-2; x[2][3]=-1;
        x[2][4]=4; x[2][5]=-3; x[2][6]=4; x[2][7]=-1;
        w[2][0][0]=-8; w[2][0][1]=-7; w[2][0][2]=4; w[2][0][3]=-5;
        w[2][1][0]=7; w[2][1][1]=0; w[2][1][2]=-6; w[2][1][3]=3;
        w[2][2][0]=-5; w[2][2][1]=-1; w[2][2][2]=1; w[2][2][3]=-4;
        w[2][3][0]=2; w[2][3][1]=7; w[2][3][2]=-3; w[2][3][3]=4;
        w[2][4][0]=-4; w[2][4][1]=-1; w[2][4][2]=-7; w[2][4][3]=-1;
        w[2][5][0]=2; w[2][5][1]=3; w[2][5][2]=-3; w[2][5][3]=5;
        w[2][6][0]=0; w[2][6][1]=-4; w[2][6][2]=-5; w[2][6][3]=3;
        w[2][7][0]=0; w[2][7][1]=4; w[2][7][2]=4; w[2][7][3]=6;
        b[2][0]=-3; b[2][1]=-4; b[2][2]=-1; b[2][3]=0;
        exp_acc[2][0]=42; exp_acc[2][1]=-21; exp_acc[2][2]=-85; exp_acc[2][3]=21;
        exp_y[2][0]=3;   exp_y[2][1]=0;   exp_y[2][2]=0;   exp_y[2][3]=1;

        // vector 3
        x[3][0]=2; x[3][1]=1; x[3][2]=3; x[3][3]=-4;
        x[3][4]=-7; x[3][5]=-1; x[3][6]=-4; x[3][7]=0;
        w[3][0][0]=1; w[3][0][1]=7; w[3][0][2]=4; w[3][0][3]=-8;
        w[3][1][0]=1; w[3][1][1]=-5; w[3][1][2]=-2; w[3][1][3]=-4;
        w[3][2][0]=-8; w[3][2][1]=-3; w[3][2][2]=4; w[3][2][3]=-8;
        w[3][3][0]=7; w[3][3][1]=-3; w[3][3][2]=3; w[3][3][3]=-5;
        w[3][4][0]=-7; w[3][4][1]=5; w[3][4][2]=0; w[3][4][3]=2;
        w[3][5][0]=-2; w[3][5][1]=-7; w[3][5][2]=-8; w[3][5][3]=-5;
        w[3][6][0]=-7; w[3][6][1]=2; w[3][6][2]=-3; w[3][6][3]=-6;
        w[3][7][0]=-1; w[3][7][1]=7; w[3][7][2]=-7; w[3][7][3]=-6;
        b[3][0]=2; b[3][1]=2; b[3][2]=-4; b[3][3]=-1;
        exp_acc[3][0]=32; exp_acc[3][1]=-22; exp_acc[3][2]=22; exp_acc[3][3]=-10;
        exp_y[3][0]=2;   exp_y[3][1]=0;   exp_y[3][2]=1;   exp_y[3][3]=0;

        // vector 4
        x[4][0]=7; x[4][1]=-4; x[4][2]=4; x[4][3]=-5;
        x[4][4]=7; x[4][5]=6; x[4][6]=0; x[4][7]=-2;
        w[4][0][0]=6; w[4][0][1]=-7; w[4][0][2]=-5; w[4][0][3]=-8;
        w[4][1][0]=-2; w[4][1][1]=-1; w[4][1][2]=5; w[4][1][3]=5;
        w[4][2][0]=1; w[4][2][1]=-3; w[4][2][2]=6; w[4][2][3]=5;
        w[4][3][0]=-5; w[4][3][1]=7; w[4][3][2]=-1; w[4][3][3]=-7;
        w[4][4][0]=2; w[4][4][1]=-4; w[4][4][2]=-4; w[4][4][3]=1;
        w[4][5][0]=0; w[4][5][1]=-4; w[4][5][2]=-2; w[4][5][3]=-6;
        w[4][6][0]=-1; w[4][6][1]=-1; w[4][6][2]=-1; w[4][6][3]=4;
        w[4][7][0]=-3; w[4][7][1]=2; w[4][7][2]=-5; w[4][7][3]=-5;
        b[4][0]=-1; b[4][1]=0; b[4][2]=1; b[4][3]=-2;
        exp_acc[4][0]=98; exp_acc[4][1]=-148; exp_acc[4][2]=-55; exp_acc[4][3]=-42;
        exp_y[4][0]=6;   exp_y[4][1]=0;   exp_y[4][2]=0;   exp_y[4][3]=0;
    endtask

    task automatic write_weights;
        for (int i = 0; i < NUM_INPUTS; i++) begin
            for (int j = 0; j < NUM_NEURONS; j++) begin
                @(posedge clk);
                #1;   // settle past this edge before driving new stimulus
                       // (blocking assigns right at the edge race the
                       // DUT's own always_ff sampling on the same edge --
                       // see docs/architecture_spec.md "testbench races")
                weight_wr_pe   = j[$clog2(NUM_NEURONS)-1:0];
                weight_wr_idx  = i[$clog2(NUM_INPUTS)-1:0];
                weight_wr_data = DATA_WIDTH'(w[vec][i][j]);
                weight_wr_en   = 1;
            end
        end
        @(posedge clk);
        #1;
        weight_wr_en = 0;
    endtask

    task automatic write_activations;
        for (int i = 0; i < NUM_INPUTS; i++) begin
            @(posedge clk);
            #1;
            act_wr_idx  = i[$clog2(NUM_INPUTS)-1:0];
            act_wr_data = DATA_WIDTH'(x[vec][i]);
            act_wr_en   = 1;
        end
        @(posedge clk);
        #1;
        act_wr_en = 0;
    endtask

    task automatic write_biases;
        for (int j = 0; j < NUM_NEURONS; j++) begin
            @(posedge clk);
            #1;
            bias_wr_pe   = j[$clog2(NUM_NEURONS)-1:0];
            bias_wr_data = ACC_WIDTH'(b[vec][j]);
            bias_wr_en   = 1;
        end
        @(posedge clk);
        #1;
        bias_wr_en = 0;
    endtask

    function automatic int signed y_slice(int j);
        y_slice = $signed(y_out[(j+1)*DATA_WIDTH-1 -: DATA_WIDTH]);
    endfunction

    task automatic check_neuron(int j, int got_acc, int got_y);
        $display("  neuron %0d: acc=%0d (expected %0d)  y=%0d (expected %0d)",
                  j, got_acc, exp_acc[vec][j], got_y, exp_y[vec][j]);
        if (got_acc !== exp_acc[vec][j]) begin
            $display("    FAILED (acc mismatch)");
            fail_count++;
        end else if (got_y !== exp_y[vec][j]) begin
            $display("    FAILED (y mismatch)");
            fail_count++;
        end else begin
            pass_count++;
        end
    endtask

    initial begin
        clk = 0; rst_n = 0; start = 0;
        weight_wr_en = 0; weight_wr_pe = 0; weight_wr_idx = 0; weight_wr_data = 0;
        act_wr_en = 0; act_wr_idx = 0; act_wr_data = 0;
        bias_wr_en = 0; bias_wr_pe = 0; bias_wr_data = 0;
        shift_in = 0;

        load_all_vectors();

        #20 rst_n = 1;
        #10;

        shift_in = 5'd4;   // matches generate_vectors.py SHIFT_INT4=4

        for (vec = 0; vec < NUM_VECTORS; vec++) begin
            $display("Test %0d: Golden INT4 vector %0d (verification/reference/vectors_int4.csv row %0d)",
                      vec + 1, vec, vec + 1);
            write_weights();
            write_activations();
            write_biases();

            @(posedge clk);
            start = 1;
            @(posedge clk);
            start = 0;
            wait (done == 1'b1);
            #1;

            // Unrolled (not a for-loop): iverilog requires a constant
            // scope index to reach into a generate-block instance by
            // hierarchical name, so gen_pe[0..3] must be named literally
            // (same constraint as tb_accelerator.sv).
            check_neuron(0, $signed(dut.gen_pe[0].pe_acc), y_slice(0));
            check_neuron(1, $signed(dut.gen_pe[1].pe_acc), y_slice(1));
            check_neuron(2, $signed(dut.gen_pe[2].pe_acc), y_slice(2));
            check_neuron(3, $signed(dut.gen_pe[3].pe_acc), y_slice(3));

            start = 0;
            @(posedge clk);
            #1;
            if (busy !== 1'b0) begin
                $display("  FAILED: busy did not drop after done deasserted by !start");
                fail_count++;
            end else begin
                pass_count++;
            end
        end

        $display("----------------------------------------");
        $display("PASSED: %0d  FAILED: %0d", pass_count, fail_count);
        if (fail_count == 0) $display("ALL TESTS PASSED");
        else $display("SOME TESTS FAILED");
        $finish;
    end

    string dfile;
    initial begin
        dfile = `DUMPFILE;
        if ($value$plusargs("DUMPFILE=%s", dfile)) ;
        $dumpfile(dfile);
        $dumpvars(0, tb_accelerator_int4);
    end

endmodule
