// Smoke testbench for rtl/accelerator_top.sv (Sprint 2 "a smoke TB is
// allowed if it helps you code" -- full golden-vector sweep + waveform
// checks belong to Sprint 3, see docs/verification.md Level 2).
//
// This loads the FIRST row of verification/reference/vectors.csv (real
// output of algorithm/generate_vectors.py, shift=8) directly into the
// RTL and checks the accelerator's four INT8 outputs against the values
// Python actually computed -- not hand-derived expectations. It also
// checks the pre-ReLU/pre-requantize INT32 accumulators against the
// vector's acc0..acc3 to localize any future mismatch to either the
// GEMV+bias stage or the ReLU+requantize stage.
`ifndef DUMPFILE
`define DUMPFILE "tb_accelerator.vcd"
`endif

module tb_accelerator;

    localparam int DATA_WIDTH  = 8;
    localparam int NUM_INPUTS  = 8;
    localparam int NUM_NEURONS = 4;
    localparam int ACC_WIDTH   = 32;
    localparam int SHIFT_WIDTH = 5;

    logic clk, rst_n, start;
    logic weight_wr_en;
    logic [$clog2(NUM_NEURONS)-1:0] weight_wr_pe;
    logic [$clog2(NUM_INPUTS)-1:0]  weight_wr_idx;
    logic signed [DATA_WIDTH-1:0]   weight_wr_data;
    logic act_wr_en;
    logic [$clog2(NUM_INPUTS)-1:0]  act_wr_idx;
    logic signed [DATA_WIDTH-1:0]   act_wr_data;
    logic bias_wr_en;
    logic [$clog2(NUM_NEURONS)-1:0] bias_wr_pe;
    logic signed [ACC_WIDTH-1:0]    bias_wr_data;
    logic [SHIFT_WIDTH-1:0]         shift_in;
    logic busy, done;
    logic [NUM_NEURONS*DATA_WIDTH-1:0] y_out;

    accelerator_top #(
        .DATA_WIDTH (DATA_WIDTH),
        .NUM_INPUTS (NUM_INPUTS),
        .NUM_NEURONS(NUM_NEURONS),
        .ACC_WIDTH  (ACC_WIDTH),
        .SHIFT_WIDTH(SHIFT_WIDTH)
    ) dut (
        .clk           (clk),
        .rst_n         (rst_n),
        .start         (start),
        .weight_wr_en  (weight_wr_en),
        .weight_wr_pe  (weight_wr_pe),
        .weight_wr_idx (weight_wr_idx),
        .weight_wr_data(weight_wr_data),
        .act_wr_en     (act_wr_en),
        .act_wr_idx    (act_wr_idx),
        .act_wr_data   (act_wr_data),
        .bias_wr_en    (bias_wr_en),
        .bias_wr_pe    (bias_wr_pe),
        .bias_wr_data  (bias_wr_data),
        .shift_in      (shift_in),
        .busy          (busy),
        .done          (done),
        .y_out         (y_out)
    );

    always #5 clk = ~clk;

    int pass_count = 0;
    int fail_count = 0;

    // ---- Golden vectors: verification/reference/vectors.csv rows 1-5 ---
    // (regenerated by algorithm/generate_vectors.py, seed=1234, shift=8;
    // re-derived independently via `python3 -c "from generate_vectors
    // import generate; ..."` when this testbench was written, not just
    // copied from the CSV, to catch transcription errors either way)
    localparam int NUM_VECTORS = 5;
    int x [0:NUM_VECTORS-1][0:7];
    int w [0:NUM_VECTORS-1][0:7][0:3];   // w[vec][i][j]
    int b [0:NUM_VECTORS-1][0:3];
    int exp_acc [0:NUM_VECTORS-1][0:3];
    int exp_y   [0:NUM_VECTORS-1][0:3];

    int vec;   // currently loaded vector index, used by write_*/check_neuron

    task automatic load_all_vectors;
        // vector 0
        x[0][0]=122;  x[0][1]=122;  x[0][2]=124;  x[0][3]=-31;
        x[0][4]=-85;  x[0][5]=108;  x[0][6]=-102; x[0][7]=-62;
        w[0][0][0]=-93; w[0][0][1]=-47; w[0][0][2]=9;   w[0][0][3]=-98;
        w[0][1][0]=75;  w[0][1][1]=-67; w[0][1][2]=73;  w[0][1][3]=-47;
        w[0][2][0]=75;  w[0][2][1]=118; w[0][2][2]=117; w[0][2][3]=-61;
        w[0][3][0]=14;  w[0][3][1]=-16; w[0][3][2]=-63; w[0][3][3]=28;
        w[0][4][0]=101; w[0][4][1]=93;  w[0][4][2]=37;  w[0][4][3]=93;
        w[0][5][0]=4;   w[0][5][1]=44;  w[0][5][2]=116; w[0][5][3]=40;
        w[0][6][0]=-116;w[0][6][1]=60;  w[0][6][2]=61;  w[0][6][3]=-71;
        w[0][7][0]=93;  w[0][7][1]=-84; w[0][7][2]=73;  w[0][7][3]=94;
        b[0][0]=-35; b[0][1]=-880; b[0][2]=-676; b[0][3]=367;
        exp_acc[0][0]=4548;  exp_acc[0][1]=-3725; exp_acc[0][2]=24424; exp_acc[0][3]=-27926;
        exp_y[0][0]=18;      exp_y[0][1]=0;       exp_y[0][2]=95;      exp_y[0][3]=0;

        // vector 1 -- exercises the INT8_MIN weight boundary (-128) and
        // three ReLU-zeroed outputs plus one positive requantized output
        x[1][0]=-118; x[1][1]=43;  x[1][2]=-93; x[1][3]=28;
        x[1][4]=12;   x[1][5]=-113;x[1][6]=-83; x[1][7]=122;
        w[1][0][0]=-25; w[1][0][1]=-16; w[1][0][2]=-12; w[1][0][3]=8;
        w[1][1][0]=-79; w[1][1][1]=-128;w[1][1][2]=37;  w[1][1][3]=-64;
        w[1][2][0]=40;  w[1][2][1]=91;  w[1][2][2]=-18; w[1][2][3]=-20;
        w[1][3][0]=-83; w[1][3][1]=60;  w[1][3][2]=50;  w[1][3][3]=108;
        w[1][4][0]=70;  w[1][4][1]=-89; w[1][4][2]=77;  w[1][4][3]=126;
        w[1][5][0]=-37; w[1][5][1]=-82; w[1][5][2]=90;  w[1][5][3]=112;
        w[1][6][0]=121; w[1][6][1]=-106;w[1][6][2]=97;  w[1][6][3]=-9;
        w[1][7][0]=-18; w[1][7][1]=84;  w[1][7][2]=103; w[1][7][3]=-57;
        b[1][0]=520; b[1][1]=738; b[1][2]=730; b[1][3]=952;
        exp_acc[1][0]=-13189; exp_acc[1][1]=17583; exp_acc[1][2]=2080; exp_acc[1][3]=-15211;
        exp_y[1][0]=0;        exp_y[1][1]=69;       exp_y[1][2]=8;      exp_y[1][3]=0;

        // vector 2
        x[2][0]=-44; x[2][1]=87;  x[2][2]=-20; x[2][3]=-14;
        x[2][4]=65;  x[2][5]=-34; x[2][6]=64;  x[2][7]=-5;
        w[2][0][0]=-126;w[2][0][1]=-105;w[2][0][2]=67;  w[2][0][3]=-70;
        w[2][1][0]=124; w[2][1][1]=9;   w[2][1][2]=-85; w[2][1][3]=59;
        w[2][2][0]=-78; w[2][2][1]=-14; w[2][2][2]=20;  w[2][2][3]=-50;
        w[2][3][0]=45;  w[2][3][1]=114; w[2][3][2]=-38; w[2][3][3]=64;
        w[2][4][0]=-57; w[2][4][1]=-8;  w[2][4][2]=-100;w[2][4][3]=-11;
        w[2][5][0]=43;  w[2][5][1]=63;  w[2][5][2]=-48; w[2][5][3]=90;
        w[2][6][0]=5;   w[2][6][1]=-53; w[2][6][2]=-65; w[2][6][3]=59;
        w[2][7][0]=1;   w[2][7][1]=79;  w[2][7][2]=70;  w[2][7][3]=99;
        b[2][0]=-507; b[2][1]=-951; b[2][2]=-163; b[2][3]=25;
        exp_acc[2][0]=11903; exp_acc[2][1]=-3313; exp_acc[2][2]=-19752; exp_acc[2][3]=7848;
        exp_y[2][0]=46;      exp_y[2][1]=0;        exp_y[2][2]=0;        exp_y[2][3]=31;

        // vector 3
        x[3][0]=45;  x[3][1]=28;  x[3][2]=54;  x[3][3]=-57;
        x[3][4]=-98; x[3][5]=-13; x[3][6]=-64; x[3][7]=7;
        w[3][0][0]=31;   w[3][0][1]=125;  w[3][0][2]=76;   w[3][0][3]=-127;
        w[3][1][0]=30;   w[3][1][1]=-77;  w[3][1][2]=-21;  w[3][1][3]=-63;
        w[3][2][0]=-121; w[3][2][1]=-41;  w[3][2][2]=65;   w[3][2][3]=-115;
        w[3][3][0]=123;  w[3][3][1]=-45;  w[3][3][2]=62;   w[3][3][3]=-78;
        w[3][4][0]=-98;  w[3][4][1]=84;   w[3][4][2]=11;   w[3][4][3]=35;
        w[3][5][0]=-22;  w[3][5][1]=-107; w[3][5][2]=-123; w[3][5][3]=-72;
        w[3][6][0]=-110; w[3][6][1]=46;   w[3][6][2]=-39;  w[3][6][3]=-94;
        w[3][7][0]=-12;  w[3][7][1]=116;  w[3][7][2]=-109; w[3][7][3]=-94;
        b[3][0]=687; b[3][1]=595; b[3][2]=-934; b[3][3]=-4;
        exp_acc[3][0]=6223; exp_acc[3][1]=-4558; exp_acc[3][2]=4128; exp_acc[3][3]=-6383;
        exp_y[3][0]=24; exp_y[3][1]=0; exp_y[3][2]=16; exp_y[3][3]=0;

        // vector 4
        x[4][0]=126; x[4][1]=-50; x[4][2]=64;  x[4][3]=-69;
        x[4][4]=119; x[4][5]=100;  x[4][6]=6;   x[4][7]=-32;
        w[4][0][0]=105;  w[4][0][1]=-109; w[4][0][2]=-80;  w[4][0][3]=-120;
        w[4][1][0]=-29;  w[4][1][1]=-10;  w[4][1][2]=83;   w[4][1][3]=95;
        w[4][2][0]=24;   w[4][2][1]=-39;  w[4][2][2]=102;  w[4][2][3]=82;
        w[4][3][0]=-75;  w[4][3][1]=114;  w[4][3][2]=-6;   w[4][3][3]=-111;
        w[4][4][0]=37;   w[4][4][1]=-52;  w[4][4][2]=-63;  w[4][4][3]=30;
        w[4][5][0]=11;   w[4][5][1]=-51;  w[4][5][2]=-25;  w[4][5][3]=-84;
        w[4][6][0]=-11;  w[4][6][1]=-2;   w[4][6][2]=-14;  w[4][6][3]=66;
        w[4][7][0]=-46;  w[4][7][1]=47;   w[4][7][2]=-79;  w[4][7][3]=-65;
        b[4][0]=-47; b[4][1]=244; b[4][2]=389; b[4][3]=-369;
        exp_acc[4][0]=28253; exp_acc[4][1]=-36156; exp_acc[4][2]=-14452; exp_acc[4][3]=-9686;
        exp_y[4][0]=110; exp_y[4][1]=0; exp_y[4][2]=0; exp_y[4][3]=0;
    endtask

    task automatic write_weights;
        for (int i = 0; i < NUM_INPUTS; i++) begin
            for (int j = 0; j < NUM_NEURONS; j++) begin
                @(posedge clk);
                #1;   // settle past this edge before driving new stimulus
                       // (blocking assigns right at the edge race the
                       // DUT's own always_ff sampling on the same edge)
                weight_wr_pe   = j[$clog2(NUM_NEURONS)-1:0];
                weight_wr_idx  = i[$clog2(NUM_INPUTS)-1:0];
                weight_wr_data = DATA_WIDTH'(w[vec][i][j]);
                weight_wr_en   = 1;
            end
        end
        @(posedge clk);
        #1;
        weight_wr_en = 0;
    endtask

    task automatic write_activations;
        for (int i = 0; i < NUM_INPUTS; i++) begin
            @(posedge clk);
            #1;
            act_wr_idx  = i[$clog2(NUM_INPUTS)-1:0];
            act_wr_data = DATA_WIDTH'(x[vec][i]);
            act_wr_en   = 1;
        end
        @(posedge clk);
        #1;
        act_wr_en = 0;
    endtask

    task automatic write_biases;
        for (int j = 0; j < NUM_NEURONS; j++) begin
            @(posedge clk);
            #1;
            bias_wr_pe   = j[$clog2(NUM_NEURONS)-1:0];
            bias_wr_data = ACC_WIDTH'(b[vec][j]);
            bias_wr_en   = 1;
        end
        @(posedge clk);
        #1;
        bias_wr_en = 0;
    endtask

    function automatic int signed y_slice(int j);
        y_slice = $signed(y_out[(j+1)*DATA_WIDTH-1 -: DATA_WIDTH]);
    endfunction

    task automatic check_neuron(int j, int got_acc, int got_y);
        $display("  neuron %0d: acc=%0d (expected %0d)  y=%0d (expected %0d)",
                  j, got_acc, exp_acc[vec][j], got_y, exp_y[vec][j]);
        if (got_acc !== exp_acc[vec][j]) begin
            $display("    FAILED (acc mismatch)");
            fail_count++;
        end else if (got_y !== exp_y[vec][j]) begin
            $display("    FAILED (y mismatch)");
            fail_count++;
        end else begin
            pass_count++;
        end
    endtask

    initial begin
        clk = 0; rst_n = 0; start = 0;
        weight_wr_en = 0; weight_wr_pe = 0; weight_wr_idx = 0; weight_wr_data = 0;
        act_wr_en = 0; act_wr_idx = 0; act_wr_data = 0;
        bias_wr_en = 0; bias_wr_pe = 0; bias_wr_data = 0;
        shift_in = 0;

        load_all_vectors();

        #20 rst_n = 1;
        #10;

        shift_in = 5'd8;   // matches generate_vectors.py SHIFT=8

        for (vec = 0; vec < NUM_VECTORS; vec++) begin
            $display("Test %0d: Golden vector %0d (verification/reference/vectors.csv row %0d)",
                      vec + 1, vec, vec + 1);
            write_weights();
            write_activations();
            write_biases();

            @(posedge clk);
            start = 1;
            @(posedge clk);
            start = 0;
            wait (done == 1'b1);
            #1;

            // Unrolled (not a for-loop): iverilog requires a constant
            // scope index to reach into a generate-block instance by
            // hierarchical name, so gen_pe[0..3] must be named literally.
            check_neuron(0, $signed(dut.gen_pe[0].pe_acc), y_slice(0));
            check_neuron(1, $signed(dut.gen_pe[1].pe_acc), y_slice(1));
            check_neuron(2, $signed(dut.gen_pe[2].pe_acc), y_slice(2));
            check_neuron(3, $signed(dut.gen_pe[3].pe_acc), y_slice(3));

            start = 0;
            @(posedge clk);
            #1;
            if (busy !== 1'b0) begin
                $display("  FAILED: busy did not drop after done deasserted by !start");
                fail_count++;
            end else begin
                pass_count++;
            end
        end

        $display("----------------------------------------");
        $display("PASSED: %0d  FAILED: %0d", pass_count, fail_count);
        if (fail_count == 0) $display("ALL TESTS PASSED");
        else $display("SOME TESTS FAILED");
        $finish;
    end

    string dfile;
    initial begin
        dfile = `DUMPFILE;
        if ($value$plusargs("DUMPFILE=%s", dfile)) ;
        $dumpfile(dfile);
        $dumpvars(0, tb_accelerator);
    end

endmodule
