"""Parse verification/simulation/tb_accelerator.vcd and render a digital
timing diagram (clk, rst_n, start, busy, done, acc_clear, mac_idx, y_out)
for the first inference (IDLE -> LOAD -> COMPUTE x8 -> DONE_S) as
docs/figures/fig03_rtl_simulation_waveform.png. Pure-stdlib VCD parsing
(no vcd library dependency) + matplotlib for the plot.

The source VCD is gitignored (*.vcd) and regenerated by scripts/run_sim.sh;
run that first if verification/simulation/tb_accelerator.vcd is missing.

Usage (from repo root, needs matplotlib):
    python3 scripts/plot_rtl_waveform.py docs/figures/fig03_rtl_simulation_waveform.png
"""
import re
import sys
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

VCD = "verification/simulation/tb_accelerator.vcd"

WANTED_NAMES = {
    "clk": "clk", "rst_n": "rst_n", "start": "start",
    "busy": "busy", "done": "done", "y_out": "y_out",
}
WANTED_DUT_NAMES = {"mac_idx": "mac_idx", "acc_clear": "acc_clear"}


def parse_vcd(path):
    id_to_name = {}
    scope_stack = []
    name_seen = {}
    with open(path) as f:
        lines = f.readlines()

    i = 0
    in_dut_scope = False
    dut_depth = None
    while i < len(lines):
        line = lines[i].strip()
        if line.startswith("$scope"):
            parts = line.split()
            scope_stack.append(parts[2] if len(parts) > 2 else "?")
            if parts[2] == "dut":
                in_dut_scope = True
                dut_depth = len(scope_stack)
        elif line.startswith("$upscope"):
            if in_dut_scope and dut_depth == len(scope_stack):
                in_dut_scope = False
            if scope_stack:
                scope_stack.pop()
        elif line.startswith("$var"):
            m = re.match(r"\$var \S+ (\d+) (\S+) (\S+)", line)
            if m:
                width, ident, name = int(m.group(1)), m.group(2), m.group(3)
                if not in_dut_scope and name in WANTED_NAMES and name not in name_seen:
                    id_to_name[ident] = (name, width)
                    name_seen[name] = True
                elif in_dut_scope and name in WANTED_DUT_NAMES and ("dut." + name) not in name_seen:
                    if len(scope_stack) - dut_depth == 0:
                        id_to_name[ident] = ("dut." + name, width)
                        name_seen["dut." + name] = True
        elif line.startswith("$enddefinitions"):
            i += 1
            break
        i += 1

    series = {name: [] for name, _w in id_to_name.values()}
    t = 0
    for line in lines[i:]:
        line = line.strip()
        if not line:
            continue
        if line.startswith("#"):
            t = int(line[1:])
            continue
        if line.startswith("$"):
            continue
        if line[0] in "01xzXZ":
            val, ident = line[0], line[1:]
            if ident in id_to_name:
                name, _w = id_to_name[ident]
                iv = 1 if val == "1" else 0
                series[name].append((t, iv))
        elif line[0] == "b":
            parts = line[1:].split()
            if len(parts) == 2:
                bits, ident = parts
                if ident in id_to_name:
                    name, _w = id_to_name[ident]
                    try:
                        iv = int(bits, 2)
                    except ValueError:
                        iv = 0
                    series[name].append((t, iv))
    return series


def to_steps(pts, tmax):
    xs, ys = [], []
    if not pts:
        return xs, ys
    pts = sorted(pts, key=lambda p: p[0])
    for k, (t, v) in enumerate(pts):
        if t > tmax:
            break
        nxt = pts[k + 1][0] if k + 1 < len(pts) else tmax
        xs += [t, min(nxt, tmax)]
        ys += [v, v]
    return xs, ys


def main():
    series = parse_vcd(VCD)
    for k, v in series.items():
        print(k, len(v), v[:6])

    start_pts = series.get("start", [])
    done_pts = series.get("done", [])
    first_start = next((t for t, v in sorted(start_pts) if v == 1), 0)
    first_done_high = next((t for t, v in sorted(done_pts) if v == 1), None)
    tmin = max(0, first_start - 25)
    tmax = (first_done_high + 30) if first_done_high else 200

    rows = ["clk", "rst_n", "start", "dut.acc_clear", "busy", "dut.mac_idx", "done", "y_out"]
    labels = ["clk", "rst_n", "start", "acc_clear", "busy", "mac_idx[2:0]", "done", "y_out[31:0]"]
    fig, axes = plt.subplots(len(rows), 1, figsize=(11, 7.5), sharex=True)
    fig.suptitle("RTL simulation waveform — accelerator_top, first inference (vector 0)\n"
                  "IDLE → LOAD → COMPUTE (mac_idx 0..7) → DONE_S  "
                  "(verification/simulation/tb_accelerator.vcd)", fontsize=10)

    bus_signals = {"dut.mac_idx", "y_out"}
    for ax, row, label in zip(axes, rows, labels):
        pts = series.get(row, [])
        xs, ys = to_steps(pts, tmax)
        if row == "y_out":
            ax.axvspan(tmin, first_done_high, color="#e5a50a", alpha=0.10)
            ax.step(xs, ys, where="post", color="#1a5fb4", linewidth=1.1)
            ax.set_ylim(-0.5, max(ys, default=1) * 1.15)
            final_val = next((v for t, v in sorted(pts) if t == first_done_high), ys[-1] if ys else 0)
            ax.annotate(f"0x{final_val:08X} (valid while done=1)",
                        (first_done_high, final_val), fontsize=8, color="#1a5fb4",
                        xytext=(4, 6), textcoords="offset points")
        elif row in bus_signals:
            ax.step(xs, ys, where="post", color="#1a5fb4", linewidth=1.3)
            ax.set_ylim(-0.5, max(ys, default=1) + 0.5)
            for t, v in pts:
                if tmin <= t <= tmax:
                    ax.annotate(str(v), (t, v), fontsize=7, color="#1a5fb4",
                                xytext=(2, 3), textcoords="offset points")
        else:
            ax.step(xs, ys, where="post", color="#26a269", linewidth=1.5)
            ax.fill_between(xs, 0, ys, step="post", color="#26a269", alpha=0.15)
            ax.set_ylim(-0.3, 1.3)
            ax.set_yticks([0, 1])
        ax.set_ylabel(label, rotation=0, ha="right", va="center", fontsize=9)
        ax.grid(axis="x", color="#dddddd", linewidth=0.6)
        ax.spines[["top", "right"]].set_visible(False)

    axes[-1].set_xlabel("simulation time (testbench units)")
    axes[-1].set_xlim(tmin, tmax)
    plt.tight_layout(rect=[0, 0, 1, 0.94])
    out = sys.argv[1] if len(sys.argv) > 1 else "fig03_rtl_simulation_waveform.png"
    plt.savefig(out, dpi=160)
    print("saved", out)


if __name__ == "__main__":
    main()
